# For a detailed explanation of what these config items do, please visit the GitHub Wiki page here: https://github.com/redstonefreak589/Honeypot/wiki#configyml
blocks-broken-before-action-taken: 1
allow-player-destruction: true
allow-explode: false
allow-enderman: false
enable-container-actions: true
kick-reason: "Kicked for breaking honeypot blocks. Don't grief!"
ban-reason: "You have been banned for breaking honeypot blocks"
warn-message: "Please don't grief builds!"
chat-prefix: "&b[Honeypot]&r"