name: Honeypot
version: '${project.version}'
author: TerrorByte
description: Creates honeypot blocks designed to prevent griefing on your server
main: me.terrorbyte.honeypot.Honeypot
api-version: 1.17
load: POSTWORLD
commands:
  honeypot:
    description: Creates or deletes a honeypot block

permissions:
  honeypot.commands:
    description: Allows a user to use honeypot commands (necessary for /honeypot create and remove)
    default: op
  honeypot.create:
    description: Allows a user to create honeypot blocks
    default: op
  honeypot.remove:
    description: Allows a user to remove honeypot blocks
    default: op
  honeypot.locate:
    description: Allows a user to see nearby honeypot blocks
    default: op
  honeypot.exempt:
    description: Exempts a player from break actions
    default: op
  honeypot.notify:
    description: Allows user to be notified of honeypot breaks
    default: op
  honeypot.reload:
    description: Allows user to reload the config
    default: op
  honeypot.update:
    description: Notifies player on join if a Honeypot plugin update is available
    default: op
  honeypot.*:
    description: Allows all honeypot permissions
    default: op
    children:
      honeypot.commands: true
      honeypot.create: true
      honeypot.remove: true
      honeypot.exempt: true
      honeypot.notify: true
      honeypot.reload: true
      honeypot.locate: true
      honeypot.update: true
